spring.application.name=desigeo-analytics-service
server.port=8086

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.datasource.hikari.connection-init-sql=SET plan_cache_mode=force_custom_plan

jwt.secret=${JWT_SECRET}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
