server.port=8087

spring.application.name=gestion-de-usuarios

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/desigeo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.backend_desigeo.gestion_de_usuarios=DEBUG
spring.datasource.hikari.connection-init-sql=SET plan_cache_mode=force_custom_plan
